name: Multi-Archetype Trading Scanner

on:
  schedule:
    # Run every weekday at 10:00 AM IST (04:30 AM UTC)
    - cron: '30 4 * * 1-5'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  run-trading-scanner:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Multi-Archetype Trading Scanner
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        echo "Starting Multi-Archetype Trading Scanner..."
        echo "Current time: $(date)"
        echo "IST time: $(TZ='Asia/Kolkata' date)"
        python scanner.py
        
    - name: Log completion status
      run: |
        echo "Scanner execution completed at $(date)"
        echo "Next scheduled run: Tomorrow at 10:00 AM IST"
